# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: deploy backend

on:
  push:
    branches:
    - develop   

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        server-id: github
      
    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: 202.120.40.8
        username: root
        port: 30550
        key: ${{ secrets.PRIVATE_KEY }}
        debug: true
        script: whoami



