name: deploy backend

on:
  push:
    branches:
    - develop   

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        server-id: github
        
    - name: Build broker with Maven
      run: mvn -B package --file ./broker/pom.xml
      
    - name: Build trader with Maven
      run: mvn -B package --file ./trader/pom.xml
      
    - name: Docker Login
      uses: docker/login-action@v1.9.0
      with:
        registry: registry.cn-hangzhou.aliyuncs.com
        username: 听说名字多长就有多拉风
        password: xxYYC1021393052
      
    - name: docker build trader-transmit
      run: |
        cd ./trader/transmit
        docker build -t registry.cn-hangzhou.aliyuncs.com/pilotage/trader-transmit:v$GITHUB_RUN_NUMBER .
        docker push registry.cn-hangzhou.aliyuncs.com/pilotage/trader-transmit:v$GITHUB_RUN_NUMBER
        
    - name: docker build trader-gateway
      run: |
        cd ./trader/gateway
        docker build -t registry.cn-hangzhou.aliyuncs.com/pilotage/trader-gateway:v$GITHUB_RUN_NUMBER .
        docker push registry.cn-hangzhou.aliyuncs.com/pilotage/trader-gateway:v$GITHUB_RUN_NUMBER
        
    - name: docker build trader-transaction
      run: |
        cd ./trader/transaction
        docker build -t registry.cn-hangzhou.aliyuncs.com/pilotage/trader-transaction:v$GITHUB_RUN_NUMBER .
        docker push registry.cn-hangzhou.aliyuncs.com/pilotage/trader-transaction:v$GITHUB_RUN_NUMBER
        
    - name: docker build trader-user
      run: |
        cd ./trader/user
        docker build -t registry.cn-hangzhou.aliyuncs.com/pilotage/trader-user:v$GITHUB_RUN_NUMBER .
        docker push registry.cn-hangzhou.aliyuncs.com/pilotage/trader-user:v$GITHUB_RUN_NUMBER
        
    - name: docker build broker-master
      run: |
        cd ./broker/master
        docker build -t registry.cn-hangzhou.aliyuncs.com/pilotage/broker-master:v$GITHUB_RUN_NUMBER .
        docker push registry.cn-hangzhou.aliyuncs.com/pilotage/broker-master:v$GITHUB_RUN_NUMBER
        
    - name: docker build broker-process
      run: |
        cd ./broker/process
        docker build -t registry.cn-hangzhou.aliyuncs.com/pilotage/broker-process:v$GITHUB_RUN_NUMBER .
        docker push registry.cn-hangzhou.aliyuncs.com/pilotage/broker-process:v$GITHUB_RUN_NUMBER
        
    - name: docker build broker-broadcast
      run: |
        cd ./broker/broadcast
        docker build -t registry.cn-hangzhou.aliyuncs.com/pilotage/broker-broadcast:v$GITHUB_RUN_NUMBER .
        docker push registry.cn-hangzhou.aliyuncs.com/pilotage/broker-broadcast:v$GITHUB_RUN_NUMBER
